### ISSUE TITLE
Timestamps break "date" command

### ISSUE THREAD

**Issue by ChloeLunn** [jaylogue/retro-fuse#1]
When adding a file to an RK05 image that's mounted on a modern system (WSL 2, Ubuntu 20.04), modern timestamps are added (or attempt to be added). This adds a minor bug with regards to the "date" command once running back in UNIX V6 where it now shows an incorrect date in an invalid format.

Easily fixed by setting the date again ("date MMddHHmmyy") when back running in UNIX.

This might just be me, but thought it was worth mentioning.

**Comment by ChloeLunn** [comment]
![date bug](https://user-images.githubusercontent.com/8646360/134350786-22a05093-c711-4211-885a-7d88fe25444b.png)

**Comment by jaylogue** [comment]
Interesting find.  Apparently this stems from a known bug in the date utility; more specifically, in the gmtime() standard library function.  The code stores the number of 8 hour periods since the epoch in a signed 16-bit number, which overflows to negative in about 30 years (so just before the turn of the century).

Noel Chiappa has a version of date.c and ctime.c that fixes this and other related bugs (http://mercury.lcs.mit.edu/~jnc/tech/V6Unix.html).  The fix is only good until 2029, however.

One minor issue is see with retro-fuse is that, while you can set file dates from a modern system while the filesystem is mounted, there is no way to set the last update time in the filesystem super block (which is used to set the system time when v6 boots).  This always gets set to the current time on the modern system.  Perhaps I should add a mount flag to force all modification times to a particular value to avoid this.

**Comment by jaylogue** [comment]
Fixed in change 39adad7.
